# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splitt <- function(X, Y, m_feature, Index, Inv_Cov_Y, Command, ff) {
    .Call('IntegratedMRF_splitt', PACKAGE = 'IntegratedMRF', X, Y, m_feature, Index, Inv_Cov_Y, Command, ff)
}

Node_cost <- function(y, Inv_Cov_Y, Command) {
    .Call('IntegratedMRF_Node_cost', PACKAGE = 'IntegratedMRF', y, Inv_Cov_Y, Command)
}

