# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

split_node <- function(X, Y, m_feature, Index, i, Model, min_leaf, Inv_Cov_Y, Command) {
    .Call('IntegratedMRF_split_node', PACKAGE = 'IntegratedMRF', X, Y, m_feature, Index, i, Model, min_leaf, Inv_Cov_Y, Command)
}

splitt <- function(X, Y, m_feature, Index, Inv_Cov_Y, Command, ff) {
    .Call('IntegratedMRF_splitt', PACKAGE = 'IntegratedMRF', X, Y, m_feature, Index, Inv_Cov_Y, Command, ff)
}

Node_cost <- function(y, Inv_Cov_Y, Command) {
    .Call('IntegratedMRF_Node_cost', PACKAGE = 'IntegratedMRF', y, Inv_Cov_Y, Command)
}

predicting <- function(Single_Model, i, xt, Variable_number) {
    .Call('IntegratedMRF_predicting', PACKAGE = 'IntegratedMRF', Single_Model, i, xt, Variable_number)
}

